name: Test
on:
  push:
    branches-ignore:
      - main
permissions:
  actions: read
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run test coverage
        run: pnpm run test:coverage

      - name: Generate coverage reports
        run: |
          pnpm run generate-coverage
          ls -l

      - name: Upload coverage reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COVERAGE_KEY }}
          path: ${{ vars.COVERAGE_PATH }}
  upload-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download coverage reports artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.COVERAGE_KEY }}
          path: ${{ vars.COVERAGE_PATH }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: itsferdiardiansa/Oxcyn
        with:
          files: ${{ vars.COVERAGE_FILE_JSON }}
          token: ${{ secrets.CODECOV_TOKEN }}
