name: Zion.io CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Testing
        run: pnpm run test:coverage
  upload-to-codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Generating coverage reports
        uses: ./.github/actions/setup
        run: pnpm run geneerate-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: itsferdiardiansa/Oxcyn
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
